repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        - id: check-added-large-files
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-toml
        - id: check-yaml
          args: ['--allow-multiple-documents']
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.8
      hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
        - id: shellcheck
